### PR TITLE
add example of setting the CMAKE_PREFIX_PATH within root CMakeLists.txt

### PR DESCRIPTION
**Pull request by rcullito**
## Motivation

related to improved documentation around: https://github.com/status-im/react-native-desktop/issues/383

using QtCreator on Linux without this path explicitly set was causing compilation errors when attempting to build the project. If it is better to set this var elsewhere (or not at all) please let me know! 

## CATEGORY
[ DOCS]

### CODE REVIEW

File: Development-linux.md [hunk 1]
```diff
@@ -30,6 +30,14 @@ Install:
 Launch `Qt Creator`, select `Tools`->`Options..`->`Build & Run`->`CMake` tab.
 Make sure that `CMake` tool is auto-detected by `Qt Creator` or add one manually.
 
+It may be necessary to add:
+
+```
+set(CMAKE_PREFIX_PATH "<path_to_Qt>/5.9.1/gcc_64/lib/cmake")
```
Comment (vkjr) [inline Development-linux.md]: @rcullito, I have `export PATH=$PATH:/Users/vkjr/Qt/5.11.2/clang_64/bin/` set (of course for your exact path) in `.bash_profile` and it is enough on mac to avoid setting CMAKE_PREFIX_PATH. Did you try that?

Comment (rcullito) [reply Development-linux.md]: thanks for responding to this @vkjr. Yes, I've always had: `/home/robert/Qt/5.9.1/gcc_64/bin` in my path, including when I first triend compiling with QtCreator yesterday. For what it's worth I also have the same path set inline above as an env var under CMAKE_PREFIX_PATH. So on linux mint, at least, I found this was necessary to explicitly set it in the CMakeLists.txt file. Although I can't say if this would affect all linux users equally. cc @MaxRis

Comment (rcullito) [reply Development-linux.md]: small update: also found this to be the case on linux after updating to 5.11.2 also

Comment (MaxRis) [reply Development-linux.md]: Time to time it makes sense to delete manually CMakeListsCache.txt and others cmake cache files from the project left from previous builds.

Comment (rcullito) [reply Development-linux.md]: ok, thanks also then @MaxRis. I too am on QtCreator 4.7.1 and upgraded my `cmake` just now from 3.5.1 to 3.13.0-rc3 and the issue is still persisting. I'll close this PR down though and remove it if this has not been a problem for others during install as I don't want to overcomplicate the documentation.
